[package]
edition = "2021"
name = "tlek"
version = "0.2.0"

[dependencies]
anyhow = "1.0.75"
clap = { version = "4.4.8", features = ["derive"] }
rand = "0.8.5"
rand_distr = "0.4.3"
ron = "0.8.1"
serde = { version = "1.0.192", features = ["derive"] }
